#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"

if [[ ! -f "$DOKKU_ROOT/$APP/RAKE-DEPLOY" ]]; then
  dokku rake-deploy:setup $APP
fi

while read line; do
	dokku run $APP bundle exec rake $line
done < "$DOKKU_ROOT/$APP/RAKE-DEPLOY"
